<div id="modalRecuperarSenha" class="modal">
    <div class="modal-content">
        <h4>Recuperar Senha</h4>
        <div class="row">
            <div class="input-field col s6">
                <i class="medium material-icons prefix">account_circle</i>
                <input name="cpf" id="cpf" type="text" required>
                <label for="cpf">CPF</label>
            </div>
            <div class="input-field col s6">
                <i class="medium material-icons prefix">mail</i>
                <input name="email" id="email" type="email" required>
                <label for="Email">Email</label>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#" class="modal-close waves-effect waves-red btn-flat">Cancelar</a>
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Recuperar</a>
    </div>
</div>