<?php if ($this->identity()):?>
<nav class="top-bar ">
                <div class="nav-wrapper " >
                    <a href="#" data-activates="slide-out" class="button-collapse">
                        <i class="material-icons">menu</i>
                    </a>
                    <div class="brand-logo">
                        <a href="/" class="page-title">Indicar um Amigo</a>
                    </div>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li>
                            <a href="/">Alterar senha</a>
                        </li>
                        <li>
                            <a href="../" data-turbolinks="false"><i class="material-icons right">exit_to_app</i>Encerrar sessão</a>
                        </li>
                    </ul>
                </div>
</nav>
<?php endif;?>