<?php echo $this->doctype(); ?>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Parceria Life'); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/materialize.min.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/asset/application/meuProjeto.css')
        ->prependStylesheet($this->basePath() . 'http://fonts.googleapis.com/icon?family=Material+Icons')
        ->prependStylesheet($this->basePath() . 'https://fonts.googleapis.com/css?family=Roboto')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/materialize.min.js')
        ->prependFile($this->basePath() . 'https://code.jquery.com/jquery-2.1.1.min.js')
        ->prependFile($this->basePath() . 'https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body class>
        <header id="menu-lateral">
            <ul id="slid-out" class="side-nav fixed">
                <li>
                    <div class="user-view">
                        <div class="background">
                            <img src="img/fundo_user.jpg">
                        </div>
                        <a href="#!user">
                            <img class="circle" src="img/cachorro.jpg">
                        </a>
                        <a href="#!name">
                            <span class="white-text name">Lucas Levino</span>
                        </a>
                        <a href="#!email">
                            <span class="white-text email">lukslevino@gmail.com</span>
                        </a>
                    </div>
                </li>
                <li>
                    <a href="/" class="waves-effect waves-teal"><i class="material-icons left">person_add</i>Indicar um
                        amigo</a>
                </li>
                <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">supervisor_account</i>Amigos
                        indicados</a>
                </li>
                </li>
                <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">account_balance</i>Informar
                        Endereço</a>
                </li>
                </li>
                <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">mood</i>Meus
                        Pontos</a>
                </li>
                </li>
                <li class="bold"><a href="/" class="waves-effect waves-teal"><i
                                class="material-icons left">group_add</i>Amigos Confirmados</a>
                </li>
                </li>
                <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">notifications_none</i>Informações</a>
                </li>
                
            </ul>
        </header>
        <main>
            <nav class="top-bar ">
                <div class="nav-wrapper " >
                    <a href="#" data-activates="slide-out" class="button-collapse">
                        <i class="material-icons">menu</i>
                    </a>
                    <div class="brand-logo">
                        <a href="/" class="page-title">Indicar um Amigo</a>
                    </div>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li>
                            <a href="/">Alterar senha</a>
                        </li>
                        <li>
                            <a href="../" data-turbolinks="false"><i class="material-icons right">exit_to_app</i>Encerrar sessão</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="content">
                <div class="left-painel">
                            <?php echo $this->content ?>
                </div>
            </div>
        </main>
        <script>
            $(document).ready(function () {
                $(".button-collapse").sideNav();

            });
        </script>
</body>
</html>
