<?php
if ($this->identity()): ?>
    <li>
        <div class="user-view">
            <div class="background">
                <img src="/img/fundo_user.jpg">
            </div>
            <a href="#!user">
                <img class="circle" src="/img/cachorro.jpg">
            </a>
            <a href="#!name">
                <span class="white-text name">Lucas Levino</span>
            </a>
            <a href="#!email">
                <span class="white-text email">lukslevino@gmail.com</span>
            </a>
        </div>
    </li>
<?php endif; ?>
<?php
//perfil usuario comum
if ($this->identity()->coFuncao == 1) { ?>
    <li>
        <a href="/" class="waves-effect waves-teal"><i class="material-icons left">person_add</i>Indicar um
            amigo</a>
    </li>
    <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">supervisor_account</i>Amigos
            indicados</a>
    </li>
    <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">account_balance</i>Informar
            Endereço</a>
    </li>
    <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">mood</i>Meus
            Pontos</a>
    </li>
    <li class="bold"><a href="/" class="waves-effect waves-teal"><i
                    class="material-icons left">group_add</i>Amigos Confirmados</a>
    </li>
    <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">notifications_none</i>Informações</a>
    </li>
    <li class="bold"><a href="/usuario/acesso" class="waves-effect waves-teal"><i class="material-icons left">account_circle</i>Login</a>
    </li>

<?php } elseif ($this->identity()->coFuncao == 2) ?>

    <li>
        <a href="/" class="waves-effect waves-teal"><i class="material-icons left">person_add</i>Verificar Indicados</a>
    </li>
    <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">supervisor_account</i>Usuarios</a>
    </li>
    <li class="bold"><a href="/" class="waves-effect waves-teal"><i class="material-icons left">account_balance</i>Relatorios</a>
    </li>
<?php else {?>
    <i class=" large material-icons">perm_identity</i>
<?php }?>