<form action="" method="post" id="loginForm">
<div class="row">
    <div class="col s12 m6">
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col s12">
                        <span class="page-title-title " style="font-size: xx-large">Login - Parceria Ortho</span>
                    </div>
                    <!--<div class="col s2">
                        <i class="large material-icons right">lock_outline</i>
                    </div>-->
                </div>
            </div>
            <hr>
            <div class="card-content">
                <div class="row">
                    <div class="input-field col s12 " required>
                        <i class="medium material-icons prefix">account_circle</i>
                        <input name="nomeUser" id="nomeUser" type="text"  maxlength="100" required autofocus>
                        <label for="nomeUsuario">Usuário</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 " required>
                        <i class="medium material-icons prefix">lock</i>
                        <input name="userPassword" id="userPassword" type="password"  >
                        <label for="userPassword">Senha</label>
                    </div>
                </div>
                <div class="action right-align">
                    <button type="submit" class="btn btn-primary">Acessar</button>
                </div>
            </div>

        </div>
    </div>
</div>
</form>