<div class="row">
    <form class="col s12 center-align" id="cadastroForm" method="POST" role="form">
        <div class="row">
            <div class="input-field col s6">
                <input name="nome" id="nome" type="text" class="validate" required>
                <label for="nome">Nome</label>
            </div>
            <div class="divider"></div>
            <div class="input-field col s6">
                <select name="tpSexo">
                    <option value="" disabled selected>Selecione</option>
                    <option value="M">Masculino</option>
                    <option value="F">Feminino</option>
                    <option value="O">Outros</option>
                </select>
                <label for="sexo">Sexo</label>
            </div>
        </div>
        <div class="row">
        <div class="input-field col s6">
            <input name="email" id="email" type="text" class="validate" required>
            <label for="email">Email</label>
        </div>
        <div class="input-field col s6">
            <input name="email_confirm" id="email_confirm" type="text" class="validate" required>
            <label for="email_confirm">Confirme o Email</label>
        </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input name="fone_cel" id="fone_cel" type="text" class="validate" required>
                <label for="fone_cel">Telefone Celular</label>
            </div>
            <div class="input-field col s6">
                <input name="fone_fixo" id="fone_fixo" type="text" class="validate" >
                <label for="fone_fixo">Telefone Fixo</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input name="endereco" id="endereco" type="text" class="validate">
                <label for="endereco">Endereço</label>
            </div>
            <div class="input-field col s6">
                <input name="ender_2" id="endereco_2" type="text" class="validate">
                <label for="endereco_2">Endereço 2</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input name="senha" id="senha" type="password" class="validate" required>
                <label for="senha">Senha</label>
            </div>
            <div class="input-field col s6">
                <input name="confirm_senha" id="senha" type="password" class="validate" required>
                <label for="senha">Confirme sua senha</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12 right-align">
                    <button id="btn-limpar" class="waves-effect waves-light btn grey lighten-1" type="reset">
                        Limpar
                    </button>
              <!--  <div class="col s3">
                    <a class="waves-effect waves-light btn red modal-trigger modal-close" href="#modal1"><i
                                class="material-icons left">clear</i>Cancelar</a>
                </div>-->
                <!--<div class="col s3">
                    <a class="waves-effect waves-light btn blue"><i class="material-icons left">mode_edit</i>Editar</a>
                </div>-->
                    <button id="btn-cadastrar" class="waves-effect waves-light btn green" type="button" name="submit">
                        <i class="material-icons left">check</i>Cadastrar
                    </button>
            </div>
        </div>
    </form>
    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>Confirmação de Cancelamento</h4>
            <fieldset>
            <p>Todas as alterações serão perdidas. Deseja realmente cancelar?</p>
            </fieldset>
        </div>
        <div class="modal-footer">
            <a class="modal-action modal-close waves-effect waves-green btn-flat">Nao</a>
            <a href="/" class="modal-action modal-close waves-effect waves-green btn-flat">Sim</a>
        </div>
    </div>
</div>


<div id="resultado"></div>
<script type="text/javascript">
    $(document).ready(function () {
        $('.modal').modal();
        $('select').material_select();
        $('#btn-cadastrar').click(function () {
            $.ajax({
                type: 'POST',
                data: $('#cadastroForm').serialize(),
                url: "/usuario/solicitarAcesso",
                success: function (data) {
                    $('#resultado').html(data);

                }
            });
        });
    });

</script>
